package Entity;
// Generated Oct 26, 2018 7:12:41 PM by Hibernate Tools 4.3.1



/**
 * Flatdetails generated by hbm2java
 */
public class Flatdetails  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String location;
     private String address;
     private String contact;
     private Integer floorNo;
     private Integer flatSize;
     private Integer badRoom;
     private Integer bathroom;
     private String drowingroom;
     private String diningroom;
     private String balcony;

    public Flatdetails() {
    }

	
    public Flatdetails(String name, String location, String address, String contact) {
        this.name = name;
        this.location = location;
        this.address = address;
        this.contact = contact;
    }
    public Flatdetails(String name, String location, String address, String contact, Integer floorNo, Integer flatSize, Integer badRoom, Integer bathroom, String drowingroom, String diningroom, String balcony) {
       this.name = name;
       this.location = location;
       this.address = address;
       this.contact = contact;
       this.floorNo = floorNo;
       this.flatSize = flatSize;
       this.badRoom = badRoom;
       this.bathroom = bathroom;
       this.drowingroom = drowingroom;
       this.diningroom = diningroom;
       this.balcony = balcony;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public Integer getFloorNo() {
        return this.floorNo;
    }
    
    public void setFloorNo(Integer floorNo) {
        this.floorNo = floorNo;
    }
    public Integer getFlatSize() {
        return this.flatSize;
    }
    
    public void setFlatSize(Integer flatSize) {
        this.flatSize = flatSize;
    }
    public Integer getBadRoom() {
        return this.badRoom;
    }
    
    public void setBadRoom(Integer badRoom) {
        this.badRoom = badRoom;
    }
    public Integer getBathroom() {
        return this.bathroom;
    }
    
    public void setBathroom(Integer bathroom) {
        this.bathroom = bathroom;
    }
    public String getDrowingroom() {
        return this.drowingroom;
    }
    
    public void setDrowingroom(String drowingroom) {
        this.drowingroom = drowingroom;
    }
    public String getDiningroom() {
        return this.diningroom;
    }
    
    public void setDiningroom(String diningroom) {
        this.diningroom = diningroom;
    }
    public String getBalcony() {
        return this.balcony;
    }
    
    public void setBalcony(String balcony) {
        this.balcony = balcony;
    }




}


